### ISSUE TITLE
Authentication: Passwordless Authentication

### ISSUE THREAD

**Issue by adius** [roschaefer/rundfunk-mitbestimmen#112]
As a user
I want to get an email with an authentication link each time I want to login
Because remembering passwords is insecure and creates obstacles

https://medium.com/@ninjudd/passwords-are-obsolete-9ed56d483eb

**Comment by roschaefer** [comment]
Yeah, I was thinking the same in #106 - however for signup instead of authentication.

At the moment I'm still struggling to find out what's the best signup/authentication pattern with the least obstacles.

**Comment by adius** [comment]
👍  ... but your commit style seems to be heavily inspired by http://whatthecommit.com 😂
