### ISSUE TITLE
(Find broadcasts | My broadcasts | Statistics): Show broadcast view on click

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#121]
```gherkin
Feature: Show broadcast modal on click
  As a user
  I would like to see a detailed view whenever I click on the title of a broadcast
  In order to recap and see the description of that broadcast again
```
**Current behaviour**

If you are logged in and visit `/broadcasts` you will see

![selection_152](https://cloud.githubusercontent.com/assets/2110676/26630849/d0a26180-4608-11e7-9b6e-1d8d75b814a3.png)

If you click on the edit button on the right you'll see the broadcast edit form

![selection_151](https://cloud.githubusercontent.com/assets/2110676/26630852/d5f689fe-4608-11e7-83f1-f37b485ea48c.png)

**Desired behaviour**
If you click on a broadcast under "My broadcasts", there should be
1. A view that just shows the broadcast data, including the description
2. A button to edit that broadcast

<img width="1278" alt="click on a broadcast title" src="https://user-images.githubusercontent.com/3679710/28419744-4d8c719e-6d60-11e7-8387-c5777ed16427.png">

**Comment by somamo** [comment]
@arun1595 Here are two design proposals for the implementation:

<img width="1260" alt="detail view" src="https://user-images.githubusercontent.com/3679710/28420061-374b18c6-6d61-11e7-9223-6747bfeeaf6a.png">
<img width="1277" alt="edit view" src="https://user-images.githubusercontent.com/3679710/28420064-3a224092-6d61-11e7-9228-2634b37f6870.png">
