### ISSUE TITLE
Decide: Show login screen before we get on the invoice page

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#130]
As a database maintainer
I want to show guest users the login screen before they actually distribute their fees
In order to create a stronger incentive for people to sign up

**Comment by somamo** [comment]
I will attach a clickable example how the user work flow might be.

**Comment by somamo** [comment]
I think the button "Login and distribute budget” is too long. Maybe it should be just “Login” and we put a sentence besides "Um deine symbolische 17,5 € zu verteilen, melde dich jetzt bitte an. “ / “Please login now and distribute you budget”.  (or something like that?)

<img width="654" alt="login with tolltip" src="https://cloud.githubusercontent.com/assets/3679710/23973207/4afe6d4a-09d5-11e7-93d7-dc5c77b6c9f1.png">


It makes sense to use a fix tooltip without any toggling.

**Comment by somamo** [comment]
<img width="661" alt="screen shot 2017-03-15 at 23 07 49" src="https://cloud.githubusercontent.com/assets/3679710/23973244/79469b50-09d5-11e7-9f8b-1bfbdae1dded.png">

Until we have implemented the new design, just remove the border with the shadow, to get enough space for the tooltip. For the mobile size we can put the tooltip above or below the login button .
