### ISSUE TITLE
Issue related to enter the git command in git shell.

### ISSUE THREAD

**Issue by ashu-22** [roschaefer/rundfunk-mitbestimmen#238]
$ git clone https://github.com/spring-projects/spring-petclinic.git
Cloning into 'spring-pet-clinic'...
remote: Counting objects: 7368, done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, err.no 10054
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by roschaefer** [comment]
@ashu-22 I think you opened a pull request in the wrong repository. In the description, you are cloning from here: https://github.com/spring-projects/spring-petclinic

**Comment by ashu-22** [comment]
No, I am going to did that thing at that time, But I never applied it.

**Comment by ashu-22** [comment]
Hello Roschaefer, How are you?
Hopefully, you are doing great work.Would be that good idea, If we got some
kind of funding for this Project.

Give me your valuable feedback.


Thanks,


Regards,
Ashish Singh Chauhan
