### ISSUE TITLE
Missing Language Translation should fallback to English

### ISSUE THREAD

**Issue by domangi** [roschaefer/rundfunk-mitbestimmen#283]
If you visit rundfunk-mitbestimmen.de with a language setting that is not defined, e.g italian, then you will see all missing translation messages, instead of falling back to a default language like English.

![image](https://user-images.githubusercontent.com/217144/30988519-d5e471a6-a49a-11e7-9cf8-666cae875f48.png)

**Comment by roschaefer** [comment]
here's the bug: https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/frontend/app/routes/application.js#L73
