### ISSUE TITLE
 Visualize/demography: Backend receives approximate age and gender

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#333]
An API request to https://api.rundfunk-mitbestimmen.de//users/213 from authenticated users with parameters `gender`, `age-group` should store both parameters *and* the current datetime, so we can derive the current age based on that.

Possible genders are:
* male
* female
* other

See this chart for a list of age groups: https://www.populationpyramid.net/germany/2017/

For the bigger picture, see this epic: #318

**Comment by mattwr18** [comment]
Closed #583
