### ISSUE TITLE
Visualize/demography: German population pyramid is displayed

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#334]
The frontend should display the current population pyramid as a placeholder. This creates more value than the current image placeholder: https://rundfunk-mitbestimmen.de/visualize/demography

Check the highcharts API how to create a population pyramid: https://www.highcharts.com/demo/bar-negative-stack.

Create a controller with `ember g controller visualize/demography` and copy and paste the chart options from the Highcharts API.

You can see other usage examples here: 
https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/frontend/app/controllers/index.js
https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/frontend/app/templates/index.hbs#L81

**Comment by mattwr18** [comment]
Closed by #583
