### ISSUE TITLE
Bundles: Remove `graphviz` as a dependency, find an alternative to generate the ER diagram

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#341]
* **I'm submitting a ...**
  * maintenance proposal

* **What is the current behavior?**
`rails-erd` from the Gemfile in `/backend` has `graphviz` as a dependency. If `graphviz` is not installed on the system, running the migrations will fail.

* **What is the expected behavior?**
Auto-generating the [The ER diagram](https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/documentation/images/er.png) is nice, but it adds an unnecessary dependency. `rails-erd` should not be part of the `Gemfile`. If possible, try to keep the functionality of updating of the ER diagram automatically.

* **What is the motivation / use case for changing the behavior?**
`graphviz` is not installed on every OS on the planet. Installing it is a burden for new team members.

* **Possible solution**
Maybe there is a service for this?

**Comment by sigu** [comment]
What do you think of including it as a dependency on the readme, not too much to ask of the team member.To install `graphiz` on a system is one line and is very unlikely to fail

**Comment by roschaefer** [comment]
OK, sure! Do you want to give the README a small update? :pencil2:

**Comment by sigu** [comment]
Sure thing, will do that before noon today (my noon 😄 ), thats like 11am your time
