### ISSUE TITLE
Update ember-simple-auth-auth0

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#355]
* **I'm submitting a ...**
  * maintenance request
Update [this line](https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/frontend/package.json#L59) to the `develop` branch of the origin.

**Comment by sigu** [comment]
This is also done 😛

**Comment by roschaefer** [comment]
yep! thanks
