### ISSUE TITLE
Generate item-to-item similarity matrix

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#392]
In order to generate [this graph here](https://rundfunk-mitbestimmen.de/visualize/graph) we need to calculate the similarities between broadcast. A similarity is a value between [0,1] and is based on how often two broadcasts were supported together vs. how often the two broadcasts were supported individually. The more often a pair of broadcasts are supported by the same people, the more similar they are. These item-to-item similarities are used by Amazons product recommendation "Other users have bought..". The keyword for your search engine is "collaborative filtering".

Our goal here is not to give recommendations but to visualize these relations with a graph. In order to do so, we need the item-to-item similarity matrix. This item-to-item matrix is potentially computation-intensive and could be generated in a background job.

Probably this gem can be a starting point: https://github.com/Pathgather/predictor

**Comment by domangi** [comment]
I think computing a simple jaccard coefficient for broadcast pairs sharing "supporters" would be sufficient. If they don't share "supporters" then their jaccard coefficient would be by definition 0.

@roschaefer What do you think about the following solution:

Let's say that the supporters of Broadcast A are all users with a **positive** impression for that broadcast.

To compute the similarity between broadcast A and broadcast B we simple take their list of supporters and divide the size of the intersection by the size of the union.

The outcome could be saved in a similarity table with three columns, one for each broadcast id, and one for the computed value. The size of this table would be maximum n * (N-1) / 2 rows (complete graph), where N is the total number of broadcasts, but in reality it is much less than that, if a 0 output is not saved to the table.

**Comment by roschaefer** [comment]
I strongly agree! That was my initial thought. I never computed and stored jaccard coeffficents and I'm not quite sure what's the most efficient way here. But I would target a specific three column table in the database and recreate it once in a while.
