### ISSUE TITLE
Passwordless login page - sending the email is not possible

### ISSUE THREAD

**Issue by immerfroehlich** [roschaefer/rundfunk-mitbestimmen#424]
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**
When I enter my email on the passwordless login page, I get the following error: "We're sorry, something went wrong when sending the email".
* **What is the expected behavior?**
Getting the email with my account information, I guess. And be able to use the website.
* **What is the motivation / use case for changing the behavior?**
The webpage is not usable. Possible users will turn away and forget about the website.

* **If the current behavior is a bug, please tell us (otherwise delete):**
  * Steps to reproduce
When you are on the front page click on "Jetzt mitbestimmen".
Then choose a show and click on "unterstützen".
Then enter your email address and click on the next icon.
  * The version of your browser, local postgresql installation and operating system
Either Firefox 57.0 or Chromium 62.0.3202.89
  * Stacktraces, related issues, suggestions how to fix
"We're sorry, something went wrong when sending the email".

**Comment by roschaefer** [comment]
Oh, thank you so much for this issue. The login procedure is difficult to test as we're using a service called Auth0 and we're very reliant on user feedback like this. Sometimes, the reason for the error is  very stupid: I checked the logs and we had numerous [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) [issues](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). We forgot to instruct Auth0 to allow our subdomain www.rundfunk-mitbestimmen.de 🤦‍

You have seen this, right?
![selection_100](https://user-images.githubusercontent.com/2110676/33243766-8ca8f090-d2ec-11e7-8847-568528d42a81.png)


That was a long-standing error and probably a hundred users did not sign up. Thank you very much for reporting!
