### ISSUE TITLE
Backend: Update broadcast similarity scores

### ISSUE THREAD

**Issue by domangi** [roschaefer/rundfunk-mitbestimmen#534]
* **I'm submitting a ...**
  * feature request

* **What is the current behavior?**
Broadcast similarity scores are calculated all from scratch when `Similarity.compute_all` method is called

* **What is the expected behavior?**
When a change to the Impressions table is made, create/update similarity scores of all affected broadcasts

* **What is the motivation / use case for changing the behavior?**
Have always updated similarity scores and avoid making unnecessary calculations.

* **What could be a possible solution? (not obligatory)**
Use an after_save callback on the impressions model that calls a new similarity class method in charge of updating all similarity scores connected to a broadcast, and call it using sidekiq's delay method, so that it's computation doesn't affect server response time:

   ``` ruby
   Similarity.delay.compute_similarities_for(broadcast_id)
   ```

**Comment by roschaefer** [comment]
Is it not already implemented [here](https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/backend/app/models/impression.rb#L19)?

**Comment by domangi** [comment]
You are right 🙈
