### ISSUE TITLE
Some icons are not rendered correctly in the page footer

### ISSUE THREAD

**Issue by domangi** [roschaefer/rundfunk-mitbestimmen#608]
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**
In the page footer icons for email, github, facebook and twitter are not visualized. Instead a square is rendered.

* **What is the expected behavior?**
Each icon should be shown correctly

* **If the current behavior is a bug, please tell us (otherwise delete):**

![image](https://user-images.githubusercontent.com/217144/39187895-bc9749a8-47ce-11e8-97aa-5d1743180fe2.png)

Tested on Chrome, Firefox and Safari

**Comment by ZmagoD** [comment]
Hi @domangi, I can't reproduce this bug, on production looks like the icons are loaded correctly.

**Comment by domangi** [comment]
@ZmagoD I think this was solved by updating the semantic-ui library in 
 this pull request https://github.com/roschaefer/rundfunk-mitbestimmen/pull/659.

I am not sure but I think there was also a problem with travis which wasn't taking the updated library in production, so it was fixed on development but the icons were still missing in production. Probably that's why this issue remained open.

I close the issue.

**Comment by roschaefer** [comment]
Yes, I think it was.. thanks for the update!
