### ISSUE TITLE
Visualize/Graph: Add Color legend to Broadcasts Relationship Graph

### ISSUE THREAD

**Issue by domangi** [roschaefer/rundfunk-mitbestimmen#613]
* **I'm submitting a ...**
  * user interface improvement

* **What is the current behavior?**
The page shows a graph that describes similarities between broadcasts, based on their Jaccard Index: an edge between two nodes is present if their similarity is above a certain threshold. Different colors are used for the nodes representing different media types, e.g. tv, radio, etc...

* **What is the expected behavior?**
A legend should be provided to understand which color represents which media type

* **What is the motivation / use case for changing the behavior?**
It provides a better understanding of the graph.

* **What could be a possible solution? (not obligatory)**
Add a color legend below the graph.

**Comment by roschaefer** [comment]
fixed by #752
