### ISSUE TITLE
Age demography : Age group range should automatically change over time

### ISSUE THREAD

**Issue by faithngetich** [roschaefer/rundfunk-mitbestimmen#636]
* **I'm submitting a ...**
  * user interface improvement

* **What is the current behavior?**
  * user has to manually change their age group once it's outdated. Age is currently stored as a string.

* **What is the expected behavior?**
  * Age group should update automatically over time. It should be stored as an integer.

* **What is the motivation/use case for changing the behavior?**
  * A user's age group should be in real-time

**Comment by mattwr18** [comment]
Closed by #583
