### ISSUE TITLE
Docker gets stuck in an endless loop when dependencies need to be installed

### ISSUE THREAD

**Issue by mattwr18** [roschaefer/rundfunk-mitbestimmen#805]
* **I'm submitting a ...**
  * bug report
 
* **What is the current behavior?**
When new changes are pulled in and one run docker-compose up, it says to run yarn install, but then when you run docker-compose up it tells you to run yarn install again, and again
* **What is the expected behavior?**
That installing the dependencies will not cause this endless loop
* **What is the motivation / use case for changing the behavior?**
So that people can use docker for local development without time spent debugging
* **If the current behavior is a bug, please tell us (otherwise delete):**
It is
* **What could be a possible solution? (not obligatory)**
Running docker-compose down -v to remove the volumes and rebuilding with docker-compose up --build seems to work; although, it needs to be confirmed that this reliably works. 
In the meeting, we were talking about the node_modules directory being watched as a possible problem.. There is this issue from GitHub that could shed some light on the issue
https://github.com/brikis98/docker-osx-dev/issues/30

**Comment by roschaefer** [comment]
I think this is closed with names volumes: https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/docker-compose.override.yml#L16

The workflow is:
1. `docker-compose down -v`
2. `docker-compose up`

Feel free to reopen if the problem persists.
