### ISSUE TITLE
Rspec, Breakman, and Rubocop Rake task

### ISSUE THREAD

**Issue by faithngetich** [roschaefer/rundfunk-mitbestimmen#837]
* **I'm submitting a ...**
  * bug report
  * user interface improvement
  * feature request
  - [x] chore

* **What is the current behavior?**
When testing out a feature Rspec, Breakman, and Rubocop are repeated actions have to be run separately.
* **What is the expected behavior?**
Have a Rake task that runs all three if them
* **What is the motivation/use case for changing the behavior?**
Rake tasks comes in handy when we have actions that occur regularly, i.e you always want to run all three commands when you're testing out your feature.

**Comment by roschaefer** [comment]
closed by @faithngetich some time ago
