### ISSUE TITLE
Create issue templates for GitHub

### ISSUE THREAD

**Issue by mattwr18** [roschaefer/rundfunk-mitbestimmen#848]
GitHub Issue creation improvement.

When people create issues, they see a generic, verbose issue template.
Must delete non-relevant information. 

We want to have template to allow people to create better issues that encourage people to be descriptive when requesting changes.

GitHub supports multiple template set up to allow for quick integration
https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by NickSchimek** [comment]
It may be good to have a template for pull requests too.
