### ISSUE TITLE
Broadcast create should not require a valid ULR

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#862]
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**
If I try create a broadcast with a given title, description and a medium (TV) on http://localhost:4200/find-broadcasts?q=titleofthebroadcastiwanttocreatexxxslkdjfsalkfdj and hit submit, I see an error with a missing translation.

* **What is the expected behavior?**
First of all, creating a broadcast without a URL should be fine. In any case, there should not be a missing translation from the backend.

* **What is the motivation / use case for changing the behavior?**
Broadcast URLS are nice, but some don't even have a website.

* **If the current behavior is a bug, please tell us (otherwise delete):**
  * Steps to reproduce
1. Search for a broadcast title that does not exist
2. Fill out the form
3. Leave out URL
4. Hit submit

![download](https://user-images.githubusercontent.com/2110676/46758114-4a7e8380-cccc-11e8-8a21-b7b920e8d00f.png)

**Comment by NickSchimek** [comment]
The same issue exists with Image URL. Well the translation is there for image URL, however if the user clicks in the text field then a validation error occurs stating that the supplied URL is not valid. 
<img width="749" alt="screenshot 2018-12-23 21 08 41" src="https://user-images.githubusercontent.com/19519317/50391257-f265f380-06f6-11e9-8d88-6559371a2f92.png">
