### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ciremoussadia** [roschaefer/rundfunk-mitbestimmen#978]
Improve the process picture by adding "SPEED" on the left And "CONFIDENCE" on the right to help the picture be more explicit.

**Comment by ciremoussadia** [comment]
@roschaefer can be this be closed as we did it yesterday?

**Comment by ciremoussadia** [comment]
close #982

**Comment by ciremoussadia** [comment]
close #982

**Comment by roschaefer** [comment]
@ciremoussadia you can close issues with keywords. But those keywords will be in the description of a *pull request*, see [Githubs autoclosing feature](https://help.github.com/articles/closing-issues-using-keywords/).
